### PR TITLE
Add history-api fallback to index.html

### LINKED ISSUE #5: Can't deep-link to cats or dogs
You can click on a cat or dog to view it, but if you try to go directly to the URL it fails:
> dog/fdca4613-9b85-4dbf-8aa5-4c45cd78e03a

> Cannot GET /dog/fdca4613-9b85-4dbf-8aa5-4c45cd78e03a

### PR DESCRIPTION
**Pull request by gnarf**
Fixes #5 probably

### CODE REVIEW

**Comment by gnarf** [comment]
Here is my "deep link":

http://canarynodebocoupdev.gardens.acquia-sites.com/dog/fdca4613-9b85-4dbf-8aa5-4c45cd78e03a

**Comment by CashWilliams** [comment]
Looks good to me. +1

**Comment by jenter** [comment]
thanks @gnarf , merging

**Comment by danepowell** [comment]
Make sure to update the lock files whenever you add a new dependency. See https://github.com/jenter/decoupled-js/pull/12

**Pull request merged**
